version: "3.3"
services:
  react:
    image: node:12.17.0
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      - NODE_ENV=production
    container_name: react_beginners_93
    command: sh -c "cd 09-routing/03-react-router && yarn start"
    ports:
      - "3000:3000"