version: "3.3"
services:
  react:
    image: node:12.17.0
    working_dir: /code
    volumes:
      - ./01-hello/02-hello:/code
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=production
    container_name: react_beginners_01
