version: "3.3"
services:
  react:
    image: node:12.17.0
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      - NODE_ENV=production
    container_name: react_beginners_10_3
    command: sh -c "cd 10-redux/03-redux && yarn start"
    ports:
      - "3000:3000"